name: HW2 github actions template

on:
  push:
    branches: [main]
    files:
      - 'hw2/**'
  pull_request:
    branches: [main]
    files:
      - 'hw2/**'

# cd hw1 and setup golang
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: |
          cd hw1
          go mod tidy

      - name: Run tests
        run: |
          cd hw1
          go test ./...

      - name: Build
        run: |
          cd hw1
          go build -o main .
